// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkx2Z7J6eXkngLHPFHuZP_Di7JP6-jP_I',
    appId: '1:501174918096:web:b179301c769b9302cfb7d5',
    messagingSenderId: '501174918096',
    projectId: 'gestor-hospital-bd',
    authDomain: 'gestor-hospital-bd.firebaseapp.com',
    storageBucket: 'gestor-hospital-bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiw9wON-99uLFi3IxhfYWojZSnDMP-Hik',
    appId: '1:501174918096:android:28814c7d5af87d50cfb7d5',
    messagingSenderId: '501174918096',
    projectId: 'gestor-hospital-bd',
    storageBucket: 'gestor-hospital-bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDflZUTHs8H8lYXXgVdN5wr_ASk-iwW-J0',
    appId: '1:501174918096:ios:9915bd8deb1ceec1cfb7d5',
    messagingSenderId: '501174918096',
    projectId: 'gestor-hospital-bd',
    storageBucket: 'gestor-hospital-bd.firebasestorage.app',
    iosBundleId: 'com.example.hospitalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDflZUTHs8H8lYXXgVdN5wr_ASk-iwW-J0',
    appId: '1:501174918096:ios:9915bd8deb1ceec1cfb7d5',
    messagingSenderId: '501174918096',
    projectId: 'gestor-hospital-bd',
    storageBucket: 'gestor-hospital-bd.firebasestorage.app',
    iosBundleId: 'com.example.hospitalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkx2Z7J6eXkngLHPFHuZP_Di7JP6-jP_I',
    appId: '1:501174918096:web:a8dba595295978d4cfb7d5',
    messagingSenderId: '501174918096',
    projectId: 'gestor-hospital-bd',
    authDomain: 'gestor-hospital-bd.firebaseapp.com',
    storageBucket: 'gestor-hospital-bd.firebasestorage.app',
  );
}
